#!/bin/sh
if test $# != 1; then
	echo
	echo "Downloads and unpacks Kadu module."
	echo "Usage: download_module <module_name>"
	echo
	exit
fi
echo
echo -e "\033[32m>>>\033[0m Downloading $1 module"
echo
KADU_VERSION=`cat ../VERSION`
MODULE_WEBSITE=`cat $1.web`
wget -N $MODULE_WEBSITE/kadu-$KADU_VERSION-$1.href
MODULE_HREF=`cat kadu-$KADU_VERSION-$1.href`
wget -N $MODULE_HREF
echo
echo -e "\033[32m>>>\033[0m Unpacking $1 module"
echo
rm -rf $1
tar -xzf `basename $MODULE_HREF`
echo -e "\033[32m>>>\033[0m Module downloaded and unpacked successfully"
echo
