#!/bin/sh
if test $# != 1; then
	echo
	echo "Downloads and unpacks Kadu module."
	echo "Usage: download_module <module_name>"
	echo
	exit 1
fi

echo
echo -e "\033[32m>>>\033[0m Downloading $1 module"
echo

KADU_VERSION=`cat ../VERSION`

MODULE_WEBSITE=`cat $1.web`
if test -z $MODULE_WEBSITE; then
	echo -e "\033[31m!!!\033[0m ERROR: Homepage for $1 module is unknown"
	echo
	exit 1
fi

if ! wget -N $MODULE_WEBSITE/kadu-$KADU_VERSION-$1.href; then
	echo -e "\033[31m!!!\033[0m ERROR: Downloading of $1 module href-file failed"
	echo
	exit 1
fi
MODULE_HREF=`cat kadu-$KADU_VERSION-$1.href`

if ! wget -N $MODULE_HREF; then
	echo -e "\033[31m!!!\033[0m ERROR: Downloading of $1 module package failed"
	echo
	exit 1
fi
echo
echo -e "\033[32m>>>\033[0m Unpacking $1 module"
echo
rm -rf $1
if ! tar -xzf `basename $MODULE_HREF`; then
	echo -e "\033[31m!!!\033[0m ERROR: Unpacking $1 module package failed"
	echo
	exit 1
fi
touch $1/.autodownloaded
echo -e "\033[32m>>>\033[0m Module downloaded and unpacked successfully"
echo
