#!/bin/bash
#################################################################
# Application Setup Script v0.1.2   (c) 2002 Kadu Team          #
# This program is free software. You can redistribute it and/or #
# modify it under the terms of the GNU General Public License   #
#################################################################


#   Definicja domy¶lnych warto¶ci dla zmiennych

APP_NAME=KADU
APP_VER=0.3.3-pre3
APP_DEF_DIR=/usr
# $1 - nazwy katalogów, $2 - Wartosci domy¶lne

#  Deklaracja funkcji

function AskForPath()
{
	echo -n "Proszê, podaæ ¶cie¿kê do $1 : "
	read -e
	if [ "$REPLY" == "" ]; then
		REPLY="$2"
	fi;
}

# $1 - scie¿ka, $2 - plik sprawdzany, $3 - prawid³owy string, $4 - nieprawid³owy string
function CheckPath()
{
	if [ -e $1/$2 ]; then
		CORRECT="$3"
	else
		CORRECT="$4"
	fi;
}

function Konfiguruj()
{
	QTDIR="$QT_DIR"
	LD_LIBRARY_PATH="$QT_DIR/lib:$LD_LIBRARY_PATH"
	export QTDIR
	KDEDIR="$KDE_DIR"
	export KDEDIR
	OPER="Configure"
	./configure "--prefix=$APP_DIR"
	WYK=$?
 if test "$WYK" -ne 0; then
        Error
	exit
 fi;
}

function Konfiguruj_bez_libgadu()
{
	QTDIR="$QT_DIR"
	LD_LIBRARY_PATH="$QT_DIR/lib:$LD_LIBRARY_PATH"
	export QTDIR
	KDEDIR="$KDE_DIR"
	export KDEDIR
	OPER="Configure"
	./configure "--prefix=$APP_DIR" " --with-existing-libgadu"
	WYK=$?
 if test "$WYK" -ne 0; then
        Error
	exit
 fi;
}

function Konfiguruj_z_ssl()
{
	QTDIR="$QT_DIR"
	LD_LIBRARY_PATH="$QT_DIR/lib:$LD_LIBRARY_PATH"
	export QTDIR
	KDEDIR="$KDE_DIR"
	export KDEDIR
	OPER="Configure"
	./configure "--prefix=$APP_DIR" " --with-openssl"
	WYK=$?
 if test "$WYK" -ne 0; then
        Error
	exit
 fi;
}

function Konfiguruj_z_debug()
{
	QTDIR="$QT_DIR"
	LD_LIBRARY_PATH="$QT_DIR/lib:$LD_LIBRARY_PATH"
	export QTDIR
	KDEDIR="$KDE_DIR"
	export KDEDIR
	OPER="Configure"
	./configure "--prefix=$APP_DIR" " --with-debug" " --with-openssl"

	WYK=$?
 if test "$WYK" -ne 0; then
        Error
	exit
 fi;
}

function Kompiluj()
{
	OPER="Kompiluj"
	make
	WYK=$?
if test "$WYK" -ne 0; then
        Error
	exit
 fi;
}

function Zainstaluj()
{	OPER="Zainstaluj"
	make install
	WYK=$?
 if test "$WYK" ;then
        Gratulacje
        exit
        else
        Error
        exit
 fi;
}

function Odinstaluj()
{
	OPER="Odinstaluj"
	make uninstall
	WYK=$?
 if test "$WYK" ;then
        Deinstal
        exit
        else
        Error
        exit
 fi;
}

function Gratulacje()
{
	clear
	echo " ============================================================================="
	echo " 		Gratulacje $APP_NAME zosta³o zainstalowane do katalogu $APP_DIR"
	echo " ============================================================================="
}

function Deinstal()
{
	clear
	echo " ============================================================================="
	echo " 		$APP_NAME zosta³o pomy¶lnie usuniête z  katalogu $APP_DIR"
	echo " ============================================================================="
}

function Error()
{
	echo -e "\a"
	echo " ============================================================================="
	echo " 		Wyst±pi³ b³±d operacja $OPER nie powiod³a siê"
	echo " ============================================================================="
}
function ShowInfo()
{
 	clear
        echo
	echo " =============================================================================="
	echo "                 PROGRAM BÊDZIE KORZYSTA£ Z PODANYCH ¦CIE¯EK :"
	CheckPath "$QT_DIR" include/qapplication.h ZNALEZIONA. "NIE ZNALEZIONA!"
	echo "     * Biblioteka QT wersja >=3.0.1, w katalogu: [$QT_DIR], $CORRECT"
	CheckPath "$KDE_DIR" include/kapp.h ZNALEZIONE. "NIE ZNALEZIONE!"
	echo "     * KDE Desktop wersja >=3.0.0, w katalogu: [$KDE_DIR], $CORRECT"
	CheckPath "$APP_DIR" bin/kadu "ZAINSTALOWANE" "NIE ZAINSTALOWANE"
	echo "     * Lokalizacja $APP_NAME w katalogu: [$APP_DIR], $CORRECT"
	echo
	echo " =============================================================================="
	echo " |                               MENU PROGRAMU                                |"
	echo " =============================================================================="
	echo " |          Naci¶nij   L  aby zobaczyæ licencje GNU.                          |"
	echo " |          Naci¶nij   Q  aby zmieniæ ¶cie¿kê do biblioteki QT.               |"
	echo " |          Naci¶nij   K  aby zmieniæ ¶cie¿kê do KDE Desktop.                 |"
	echo " |          Naci¶nij   D  aby zmieniæ lokalizacje $APP_NAME .                      |"
	echo " |          Naci¶nij   I  aby rozpocz±æ instalacjê                            |"
	echo " |          Naci¶nij   U  aby odinstalowaæ $APP_NAME.                              |"
	echo " |          Naci¶nij   B  aby rozpocz±æ instalacjê bez libgadu.               |"
	echo " |          Naci¶nij   S  aby rozpocz±æ instalacjê z szyfrowaniem w SSL.      |"
	echo " |          Naci¶nij   G  aby rozpocz±æ instalacjê z debug i SSL.             |"
	echo " |          Naci¶nij   P  aby uzyskaæ Pomoc za pomoc± programu Links.         |"
	echo " |          Naci¶nij   E  aby zakoñczyæ program instalacyjny.                 |"
	echo " =============================================================================="
        echo "                 UWAGA!!! musisz mieæ uprawnienia administratora"
}

function Szuk_kadu
{
APP_DIR=`find $HOME -path */bin/kadu -type f | sed -e 's/\/bin\/kadu$//' -e q`
if [ "$APP_DIR" == "" ]; then
APP_DIR=`find /usr -path */bin/kadu -type f | sed -e 's/\/bin\/kadu$//' -e q`
fi;
if [ "$APP_DIR" == "" ]; then
APP_DIR=`find /opt -path */bin/kadu -type f | sed -e 's/\/bin\/kadu$//' -e q`
fi;
if [ "$APP_DIR" == "" ]; then
APP_DIR="$APP_DEF_DIR"
fi;
}

function Szuk_QT
{
QT_DIR=`find /usr -path */include/qapplication.h -type f | sed -e 's/\/include\/qapplication.h$//' -e q`
if [ "$QT_DIR" == "" ]; then
QT_DIR=`find /opt -path */include/qapplication.h -type f | sed -e 's/\/include\/qapplication.h$//' -e q`
fi;
}

function Szuk_KDE
{
KDE_DIR=`find /usr -path */include/kapp.h -type f | sed -e 's/\/include\/kapp.h$//' -e q`
if [ "$KDE_DIR" == "" ]; then
KDE_DIR=`find /opt -path */include/kapp.h -type f | sed -e 's/\/include\/kapp.h$//' -e q`
fi;
}

#########################################################################################
#                                                       START PROGRAMU                                                                     #
#########################################################################################
clear
echo
	echo " =============================================================================="
	echo "            Witaj w $APP_NAME wersja $APP_VER Skrypt instalacyjny v0.1.2"
	echo "  Skrypt ten konfiguruje, kompiluje, instaluje lub odinstalowywuje $APP_NAME ."
	echo " =============================================================================="
	echo
	echo " Ten program jest wolnym oprogramowniem. Mo¿na go rozprowadzaæ i modyfikowaæ"
	echo " zgodnie z licencj± GNU General Public License opublikowan± przez Free Software"
	echo " Foundation w wersji 2 z pó¼niejszymi zmianami"
	echo
        echo " =============================================================================="
        echo
        echo " Konfigurujê program instalacyjny to mo¿e chwilê potrwaæ b±d¼ cierpliwy"
	echo
	echo "Szukam  KADU..."
		Szuk_kadu
	echo "Szukam  QT..."
		Szuk_QT
	echo "Szukam KDE..."
		Szuk_KDE

########################################################################################
#					SEKCJA WYBORU MENU										#
########################################################################################
while [ 1 ]; do
	ShowInfo
	while [ 1 ]; do
		read -n 1 -s
		if [[ ("$REPLY" == "L") || ("$REPLY" == "l") ]]; then
			clear
			cat COPYING | more
			break
		fi;
		if [[ ("$REPLY" == "Q") || ("$REPLY" == "q") ]]; then
			AskForPath "biblioteki QT"
			QT_DIR="$REPLY"
			break
		fi;
		if [[ ("$REPLY" == "K") || ("$REPLY" == "k") ]]; then
			AskForPath "KDE Desktop"
			KDE_DIR="$REPLY"
			break
		fi;
		if [[ ("$REPLY" == "D") || ("$REPLY" == "d") ]]; then
			AskForPath "$APP_NAME"
			APP_DIR="$REPLY"
                        break
		fi;
		if [[ ("$REPLY" == "I") || ("$REPLY" == "i") ]]; then
			Konfiguruj
			Kompiluj
			Zainstaluj
		fi;
		if [[ ("$REPLY" == "B") || ("$REPLY" == "b") ]]; then
			Konfiguruj_bez_libgadu
			Kompiluj
			Zainstaluj
		fi;
		if [[ ("$REPLY" == "S") || ("$REPLY" == "s") ]]; then
			Konfiguruj_z_ssl
			Kompiluj
			Zainstaluj
		fi;
		if [[ ("$REPLY" == "G") || ("$REPLY" == "g") ]]; then
			Konfiguruj_z_debug
			Kompiluj
			Zainstaluj
		fi;
		if [[ ("$REPLY" == "U") || ("$REPLY" == "u") ]]; then
			Konfiguruj
			Kompiluj
			Odinstaluj
		fi;
		if [[ ("$REPLY" == "E") || ("$REPLY" == "e") ]]; then
			exit
		fi;
		if [[ ("$REPLY" == "P") || ("$REPLY" == "p") ]]; then
			links ./doc/index_doc.html
			break
		fi;
	done
done
########################################################################################
#					KONIEC													 #
########################################################################################
