#cmakedefine DEBUG 1
#cmakedefine DEBUG_ENABLED 1

#define KADU_DATADIR "${KADU_DATADIR}"
#define KADU_LIBDIR "${KADU_LIBDIR}"
#define KADU_BINDIR "${KADU_BINDIR}"

#define VERSION "${KADU_VERSION}"
#define BUILD_DESCRIPTION "${BUILD_DESCRIPTION}"
#define NUMERIC_VERSION ${NUMERIC_VERSION}

#cmakedefine SIG_HANDLING_ENABLED
#cmakedefine HAVE_EXECINFO
