.\" Zmodyfikowa³ orygina³ kadu.1
.\" Piotr 'Sajmon' Simon <sajmon@tenboard.com>
.\" http://www.tenboard.com
.\"
.TH Kadu Kadu
.LO 1
.SH Opis Kadu
Kadu \- Klient gadu-gadu dla Linuksa www.kadu.net
.br
bazuje na QT3, libgadu
.br
.br
Kadu powsta³o w sierpniu 2001 roku,jako ma³a wprawka do programowania w KDE, na bazie libgg.so Wojtka Kaniewskiego.
.br
Z czasem program przekszta³ci³ siê w jeden z najpopularniejszych klientów GG dla Linuxa...
.br
Pocz±wszy od wersji 0.3.3 Kadu nie wymaga ju¿ bibliotek KDE
.br
i mo¿e byæ bez problemu u¿ywane w innych ¶rodowiskach.
.br
Pamiêtaj, Kadu to darmowe oprogramowanie. Autorzy po¶wiêcaj± swój prywatny czas na rozwój aplikacji.
.br
Miej to na wzglêdzie, prosz±c ich o co¶ lub mieszaj±c z b³otem.
.br
.SH Autorzy:
.br
Tomasz 'tomee' Jarzynka <tomee@cpi.pl>
.br
Tomasz 'chilek' Chiliñski <chilek@chilan.com>
.br
Adrian 'adrians' Smarzewski <adrians@aska.com.pl>
.br
Dariusz 'mast3r' Jagodzik <mast3r@kadu.net>
.br
Roman 'Ron_K' Krzystyniak <Ron_K@tlen.pl>
.br
.br
a tak¿e:
.br
.br
Arek Mi¶kiewicz
.br
Krzysztof Godlewski
.br
Mariusz Witkowski
.br
Mateusz Papiernik
.br
Artur Zabroñski
.br
.br
i inni.
.SH Download
.B CVS
.br
Dostêp do CVS-a poprzez WWW http://www.kadu.net/cgi-bin/cvsweb.cgi/kadu/
.br
Aby skorzystaæ z eksperymentalnego CVS-a Kadu w trybie tekstowym piszemy:
.br
.B
cvs -d:pserver:anonymous(at)kadu.net:/usr/src/kadu login
.br
a potem:
.br
.B
cvs -z3 -d:pserver:anonymous(at)kadu.net:/usr/src/kadu co kadu
.br
W obrêbie katalogu kadu na w³asnym dysku nie potrzeba u¿ywaæ parametru -d...
.br
.br
.B
¬ród³a
.br
http://www.kadu.net/releases/
.br
.br
.B
Snapshot
.br
http://www.kadu.net/snapshots/
.br
.B
Debian
.br
http://www.kadu.net/distributions/debian/
.br
.B
Gentoo
.br
http://www.kadu.net/distributions/gentoo
.br
.B
Mandrake
.br
http://www.kadu.net/distributions/mandrake
.br
.B
PLD
.br
http://www.pld.tares.one.pl/
.br
.B
RedHat
.br
http://www.kadu.net/distributions/redhat
.br
.B
Slackware
.br
http://www.kadu.net/distributions/slackware
.br
.B
SuSE
.br
http://www.kadu.net/distributions/suse
.br
.br
.B
	Wersje przestarza³e niewspierane:
.br
Pakiety binarne (w kolejno¶ci Mandrake(Leszek Czajka) / rózne dystrybucje))
.br
ftp://ftp.mimuw.edu.pl/People/lczajka/kadu
.br
ftp://ftp.pld.org.pl/software/kadu/RPM
.br
.br
.B
	Dodatki:
.br
Internetowy Instalator Kadu
(Wymaga TCL/TK w wersji 8.3.5 lub wy¿szej)
http://www.kadu.net/additions/kadu.tcl
.br
.B
Emotikony
.br
kadu 0.3.4-preX
.br
http://www.kadu.net/additions/zestaw288.tar.bz2
.br
kadu 0.3.3
.br
http://www.kadu.net/additions/kadu-gg5.0.tar.gz
.br
.B
Ikony programu
.br
(tomee, Wrzesieñ 2002)
.br
http://www.kadu.net/additions/kadu-iconpack.tgz
.br
Koncept-32 (tylko ta jedna (tomee, Pa¼dziernik 2002))
.br
http://www.kadu.net/additions/K-32.png
.br
Zestaw ikon na bazie gg3d (jok3, Lipiec 2003
.br
http://www.kadu.net/additions/gg3d.tar.gz
.br
.B
D¼wiêki
.br
http://www.kadu.net/additions/kadu-sounds.tar.gz
.SH Dokumentacja:
.br
http://www.kadu.net/index_doc.html
.SH B³êdy:
.br
B³êdy zg³aszaj na adres e-mail autorów lub na
.br
forum - http://www.kadu.net/forum/
.SH Licencja:
Kadu jest na licencji GPL
