@ECHO OFF

set PWD=%CD%
set INCLUDE_DIR=%PWD%\includes
set FINAL_SRC=%PWD%\final.cpp

ECHO /* AUTOGENERATED */ > %FINAL_SRC%
ECHO REM AUTOGENERATED  > regerate_final.bat

RD %INCLUDE_DIR% /S /Q
MKDIR %INCLUDE_DIR%

ECHO "INCLUDE_DIR: %INCLUDE_DIR%"
ECHO "CURRENT_DIR: %PWD%"

FOR /d /r %%D IN (*) DO (
	IF EXIST %%D\*.h (
		xcopy %%D\*.h  %INCLUDE_DIR%\ /C /H /R /Y
	)
)

xcopy os\qtsingleapplication\*.cpp %INCLUDE_DIR%\ /C /H /R /Y
xcopy exports.h ..\..\ /C /H /R /Y

ECHO "Done"
