#!/bin/bash

#
# Wykonanie cvs commit na wszystkich plikach, które bêd± modyfikowane przez
# skrypt configure-gen w odpowiedniej kolejno¶ci. Uruchamiaæ z katalogu wy¿ej.
#

if test -z "$1"; then
	echo "Usage: configure-commit <log_message>"
	exit 1
fi

cvs commit -f -m "$1" \
	aclocal.m4 stamp-h.in kadu-config.h.in stamp-h configure \
	Makefile.in kadu/Makefile.in translations/Makefile.in varia/Makefile.in modules/Makefile.in
