#!/bin/bash

$QTDIR/bin/lupdate -noobsolete -verbose ../kadu-core/*.cpp -ts kadu_it.ts
$QTDIR/bin/lupdate -noobsolete -verbose ../kadu-core/*.cpp -ts kadu_pl.ts
$QTDIR/bin/lupdate -noobsolete -verbose ../kadu-core/*.cpp -ts kadu_en.ts
$QTDIR/bin/lupdate -noobsolete -verbose ../kadu-core/*.cpp -ts kadu_de.ts
$QTDIR/bin/lupdate -noobsolete -verbose ../kadu-core/*.cpp -ts kadu_fr.ts