#!/bin/sh

RET=0
MODULE=$1

KADU_VERSION=`cat VERSION`

KADU_VERSION=`echo $KADU_VERSION | sed s/-.*//`

if wget -q -T 20 -t 2 -N http://kadu.net/autopatch/$KADU_VERSION/$MODULE.patch; then
	echo -e "\033[32m>>>\033[0m Patching module $MODULE"
	patch -sfN -p0 < $MODULE.patch && rm -f $MODULE.patch
	RET=$((RET+1))
fi

exit $RET
