#!/bin/sh

# KADU-MOZILLA v1.1
# Copyright (C) 2003,2004 Kadu Team

# Skrypt ten umo¿liwia bezproblemowe otwieranie url-i z
# okna Chat Kadu w Mozilli. Url podany jako argument jest
# otwierany w istniej±cej instancji Mozilli lub je¶li
# istnieje taka konieczno¶æ uruchamiana jest nowa.

ret=`mozilla -remote "openUrl($1,new-tab)" 2>&1 | grep "No running window found."`
if test -n "$ret"; then
	mozilla $1
fi;
